version: "3"

services:
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8000:8000"

  streamlit_ui:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    ports:
      - "8501:8501"

